const model = {
  version: 4,
  graph: {
    nodes: [
      {
        id: "n1",
        label: "Pressure to Deliver",
        x: 100,
        y: 200,
        radius: 40,
        min: 0,
        max: 100,
        initial: 20,
        sizeTier: "m",
        colourTier: "red",
      },
      {
        id: "n2",
        label: "Feature Velocity",
        x: 400,
        y: 200,
        radius: 40,
        min: 0,
        max: 100,
        initial: 50,
        sizeTier: "m",
        colourTier: "yellow",
      },
      {
        id: "n3",
        label: "Defects in Code",
        x: 700,
        y: 200,
        radius: 40,
        min: 0,
        max: 100,
        initial: 10,
        sizeTier: "m",
        colourTier: "orange",
      },
      {
        id: "n4",
        label: "Code Quality",
        x: 550,
        y: 450,
        radius: 40,
        min: 0,
        max: 100,
        initial: 70,
        sizeTier: "m",
        colourTier: "green",
        annotation: "Inverse of defects",
      },
      {
        id: "n5",
        label: "Cheap Hiring Rate",
        x: 250,
        y: 500,
        radius: 40,
        min: 0,
        max: 100,
        initial: 0,
        sizeTier: "m",
        colourTier: "red",
        annotation: "Quick fix",
      },
      {
        id: "n6",
        label: "Low-skill Devs",
        x: 100,
        y: 650,
        radius: 40,
        min: 0,
        max: 100,
        initial: 20,
        sizeTier: "m",
        colourTier: "orange",
      },
      {
        id: "n7",
        label: "Great Programmers",
        x: 700,
        y: 500,
        radius: 40,
        min: 0,
        max: 100,
        initial: 40,
        sizeTier: "m",
        colourTier: "blue",
        annotation: "Mentors",
      },
      {
        id: "n8",
        label: "Mentoring Capacity",
        x: 850,
        y: 650,
        radius: 40,
        min: 0,
        max: 100,
        initial: 60,
        sizeTier: "m",
        colourTier: "teal",
      },
    ],
    edges: [
      {
        kind: "causal",
        id: "e1",
        from: "n1",
        to: "n5",
        polarity: 1,
        weight: 3,
        delay: "none",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e2",
        from: "n1",
        to: "n2",
        polarity: 1,
        weight: 2,
        delay: "none",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e3",
        from: "n5",
        to: "n6",
        polarity: 1,
        weight: 2,
        delay: "short",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e4",
        from: "n2",
        to: "n3",
        polarity: 1,
        weight: 2.5,
        delay: "short",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e5",
        from: "n3",
        to: "n4",
        polarity: -1,
        weight: 2,
        delay: "medium",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e6",
        from: "n4",
        to: "n2",
        polarity: 1,
        weight: 1.5,
        delay: "none",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e7",
        from: "n6",
        to: "n4",
        polarity: -1,
        weight: 2,
        delay: "none",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e8",
        from: "n6",
        to: "n8",
        polarity: -1,
        weight: 2,
        delay: "short",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e9",
        from: "n7",
        to: "n4",
        polarity: 1,
        weight: 2,
        delay: "none",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e10",
        from: "n4",
        to: "n7",
        polarity: 1,
        weight: 1.5,
        delay: "medium",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e11",
        from: "n8",
        to: "n7",
        polarity: 1,
        weight: 1,
        delay: "long",
        transferFn: "linear",
      },
      {
        kind: "causal",
        id: "e12",
        from: "n7",
        to: "n8",
        polarity: 1,
        weight: 1,
        delay: "none",
        transferFn: "linear",
      },
    ],
    annotations: [
      {
        id: "a1",
        x: 150,
        y: 80,
        text: "QUICK FIX: pressure → cheap hiring → defects → quality crashes",
      },
      {
        id: "a2",
        x: 600,
        y: 80,
        text: "SUSTAINABLE: quality → attract mentors → improve velocity",
      },
    ],
  },
};
console.log(Buffer.from(JSON.stringify(model)).toString("base64"));
